DROP TABLE IF EXISTS student cascade;
CREATE TABLE student (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar not null
);

DROP TABLE IF EXISTS class cascade;
CREATE TABLE class (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar not null
);

DROP TABLE IF EXISTS student_class cascade;
CREATE TABLE student_class (
  student_id INTEGER,
  FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
  class_id INTEGER,
  FOREIGN KEY (class_id) REFERENCES class(id) ON DELETE CASCADE,
  CONSTRAINT student_class_pkey PRIMARY KEY (student_id, class_id)
);
