DROP TABLE IF EXISTS student cascade;
CREATE TABLE student (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar not null
);
DROP TABLE IF EXISTS class cascade;
CREATE TABLE class (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar not null
);
DROP TABLE IF EXISTS enrolement cascade;
CREATE TABLE enrolement (
  student_id INTEGER,
  FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
  class_id INTEGER,
  FOREIGN KEY (class_id) REFERENCES class(id) ON DELETE CASCADE,
  CONSTRAINT enrolement_pkey PRIMARY KEY (student_id, class_id)
);
DROP INDEX IF EXISTS class_id_idx;
CREATE INDEX IF NOT EXISTS class_id_idx on enrolement(class_id);
INSERT INTO
  student(name)
values
  ('Scott');
INSERT INTO
  student(name)
values
  ('Fraser');
INSERT INTO
  student(name)
values
  ('Jamie');
INSERT INTO
  class(name)
values
  ('Mechanics');
INSERT INTO
  class(name)
values
  ('Heat Transfer');
INSERT INTO
  class(name)
values
  ('Fluids Mechanics');
INSERT INTO
  class(name)
values
  ('Electronics');
